---
# tasks file for geo_replication
# Set the georepuser variable. If not defined default to root
- name: Set Geo-replication user
  set_fact:
     georepuser: "{{ gluster_features_georep_user | default('root') }}"

# Generate temporary file for storing the keys
- name: Create temporary storage directory
  tempfile:
    state: directory
    suffix: _georep
  register: result
  delegate_to: 127.0.0.1
  run_once: True

- name: Get the name of the directory created
  set_fact:
     georep_base_dir: "{{ result['path'] }}"
  run_once: True

# Run only on masternode
- name: Setup shared storage and generate keys
  import_tasks: georep_session_create.yml
  when: >
    gluster_features_georep_mastervol is defined and
    gluster_features_georep_slavevol is defined
  tags:
    - georep_session_create

# Run only on masternode
- name: Stop geo_rep session
  import_tasks: georep_session_stop.yml
  when: >
    gluster_features_georep_mastervol is defined and
    gluster_features_georep_slavevol is defined and
    gluster_features_georep_session_delete is not defined
  tags:
    - georep_session_stop

# Run only on masternode
- name: Delete geo_rep session
  import_tasks: georep_session_delete.yml
  when: >
    gluster_features_georep_session_delete is defined and
    gluster_features_georep_mastervol is defined and
    gluster_features_georep_slavevol is defined
  tags:
    - georep_session_delete
