---
# tasks file for nfs_ganesha
# Generate temporary file for storing the keys
- name: Create temporary storage directory
  tempfile:
    state: directory
    suffix: _ganesha
  register: result
  delegate_to: 127.0.0.1
  run_once: True

- name: Get the name of the directory created
  set_fact:
     ganesha_tmp_dir: "{{ result['path'] }}"
     ganesha_ha_base_dir: '/var/run/gluster/shared_storage/nfs-ganesha'
  run_once: True

- name: check if gluster_features_ganesha_clusternodes is set
  fail:
    msg: "Variable gluster_features_ganesha_clusternodes has to be defined"
  when: gluster_features_ganesha_clusternodes is not defined

# Run this on all the nodes
- name: Pre-requisites for setting up NFS Ganesha
  import_tasks: prerequisites.yml
  when: gluster_features_ganesha_clusternodes is defined
  ignore_errors: true
  tags:
    - prerequisites

- name: check if gluster_features_ganesha_masternode is set
  fail:
    msg: "Variable gluster_features_ganesha_masternode has to be defined"
  when: gluster_features_ganesha_masternode is not defined

# The base directory has to be one of the directories unique in /tmp/
# Generated in the main.yml of the task
- name: Copy the ssh keys to the local machine
  fetch: src=/var/lib/glusterd/nfs/{{item}}
         dest= "{{ ganesha_tmp_dir }}"
  with_items:
     - secret.pem.pub
     - secret.pem
  delegate_to: "{{ gluster_features_ganesha_masternode }}"

- name: check if gluster_features_ganesha_newnodes_vip is set
  fail:
    msg: "Variable gluster_features_ganesha_newnodes_vip has to be defined"
  when: gluster_features_ganesha_newnodes_vip is not defined

# Run on all the nodes
- name: Distribute the keys to nodes
  import_tasks: distribute_keys.yml
  when:
    - gluster_features_ganesha_clusternodes is defined
    - gluster_features_ganesha_newnodes_vip is undefined
  ignore_errors: true
  tags:
    - distributekeys

# New cluster creation, run only on masternode
#
- name: Setup shared storage and generate keys
  import_tasks: master_tasks.yml
  when:
    - gluster_features_ganesha_masternode is defined
    - gluster_features_ganesha_newnodes_vip is undefined
  delegate_to: "{{ gluster_features_ganesha_masternode }}"
  run_once: True
  ignore_errors: true
  tags:
    - mastersetup

# Run only on masternode
# delegate_to is not necessary if the first node is used as master
- name: Enable NFS Ganesha cluster
  import_tasks: enable_ganesha.yml
  when:
    - gluster_features_ganesha_masternode is defined
    - gluster_features_ganesha_newnodes_vip is undefined
  ignore_errors: true
  delegate_to: "{{ gluster_features_ganesha_masternode }}"
  run_once: True
  tags:
    - enableganesha

# Add nodes to existing ganesha cluster
#
- name: Add nodes to Ganesha cluster
  import_tasks: add_new_nodes.yml
  when: gluster_features_ganesha_newnodes_vip is defined
  delegate_to: "{{ gluster_features_ganesha_masternode }}"
  run_once: Ture
  tags:
    - ganesha_addnodes

# Ensure to delete the temporary directory
- name: Delete the temporary directory
  file:
     state: absent
     path: "{{ ganesha_tmp_dir }}"
  delegate_to: 127.0.0.1
  run_once: True
